version: '3'

services:
  smtp:
    image: purwandi/mailbox:1.0.3
    container_name: mailbox
    restart: unless-stopped
    environment:
      APP_KEY:
      HTTP_PORT: 8080
      SMTP_PORT: 2525
      MAIL_HOSTNAME: localhost
      MAIL_AUTH: "true"
      MAIL_USERNAME: foo@bar.com
      MAIL_PASSWORD: password
      MAIL_TLS: "true"
      MAIL_TLS_CERT: ./cert/certificate.crt
      MAIL_TLS_KEY: ./cert/certificate.key
    ports:
      - 8080:8080
      - 2525:2525
    volumes:
      - ./cert:/workspace/cert
      - ./assets:/workspace/public/assets
