name: Build docker image

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.4'
    - run: go test ./...
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: purwandi/mailbox:latest
    - run: docker push purwandi/mailbox
