name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
    - uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: docker.pkg.github.com/purwandi/mail/mailbox:${{ env.RELEASE_VERSION }}
    - run: docker images
    - run: docker push docker.pkg.github.com/purwandi/mail/mailbox
